delete Http://localhost:3001/api/notes/658c639136bb6b216f39d096

####

get Http://localhost:3001/api/notes

####

post http://localHost:3001/api/notes
content-Type:application/json

{ 
    "content":"Andre esta aprendendo",
    "important":false
}

####

get http://localhost:3001/api/notes/658c639136bb6b216f39d096

#####

put http://localhost:3001/api/notes/658b18f101bf2eba87c22a57
content-type:application/json

{
    "content":"is not dificult , it is so easy",
    "important":true
}